library(survival)
library(survminer)
library(dplyr)
data(ovarian)
ovarian$rx <- factor(ovarian$rx, levels= c("1","2"),labels=c("A","B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, levels= c("1","2"),labels=c("no","yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, levels= c("1","2"),labels=c("good","bad"))
help(ovarian)
glimpse(ovarian)
library(riskRegression)
glimpse(ovarian)
hist(ovarian$age)
ovarian <- ovarian %>% mutate(age_group=ifelse(age>=500,"old","young"))
glimpse(ovarian)
ovarian <- ovarian %>% mutate(age_group=ifelse(age>=50,"old","young"))
ovarian$age_group<-factor(ovarian$age_group)
ovarian <- ovarian %>% mutate(age_group=ifelse(age>=65,"old","young"))
ovarian$age_group<-factor(ovarian$age_group)
glimpse(ovarian)
ovarian <- ovarian %>% mutate(age_group=ifelse(age>=20,"old","young"))
ovarian <- ovarian %>% mutate(age_group=ifelse(age>=49,"old","young"))
ovarian$age_group<-factor(ovarian$age_group)
surv_object <- Surv(time=ovarian$futime,event=ovarian$fustat)
surv_object
fit1 <- survfit(surv_object ~ rx, data=ovarian)
fit1 %>% summary()
ggsurvplot(fit1, data=ovarian, pval = TRUE)
fit_coxph <-coxph(Surv(time=ovarian$futime,event=ovarian$fustat) ~ rx+resid.ds+age_group+ecog.ps, data=ovarian, method = "breslow", x=TRUE)
baseH1 <- predictCox(fit_coxph)
as.data.table(baseH1[c("cumhazard","strata","survival")])
predictCox(fit_coxph, newdata = ovarian, times=c(3,5)*365)
autoplot(baseH2,type = "survival")
ggforest(fit_coxph, data=ovarian)


View(fit_coxph)
